# Generated by Django 5.0.1 on 2024-02-07 17:16

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        ('organizations', '0002_delete_workhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Administrator', 'verbose_name_plural': 'Admins'},
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='manager_supervisor',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='appointment date'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_reason',
            field=models.TextField(blank=True, null=True, verbose_name='appointment reason'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_status',
            field=models.CharField(blank=True, default='Pending', max_length=30, null=True, verbose_name='appointment status'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True, verbose_name='appointment time'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='adminuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subordinates', to='employees.adminuser'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organizations.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(blank=True, null=True, verbose_name='date of employment'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('--Select--', '--Select--'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Volunteer', 'Volunteer'), ('Temporary', 'Temporary'), ('Seasonal', 'Seasonal'), ('Freelance', 'Freelance'), ('Remote', 'Remote'), ('Disabled', 'Disabled'), ('Other', 'Other')], max_length=20, null=True, verbose_name='employee status'),
        ),
        migrations.CreateModel(
            name='WorkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=100, verbose_name='job role')),
                ('job_description', models.TextField(verbose_name='job description')),
                ('start_date', models.DateField(default=datetime.datetime.now, verbose_name='start date')),
                ('end_date', models.DateField(default=datetime.datetime.now, verbose_name='end date')),
                ('reason_for_leaving', models.TextField(blank=True, null=True, verbose_name='reason for leaving')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_history', to='organizations.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_history', to='employees.employee')),
            ],
            options={
                'verbose_name': 'work history',
                'verbose_name_plural': 'work histories',
                'ordering': ['-end_date'],
            },
        ),
    ]
