# Generated by Django 5.0.1 on 2024-02-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_adminuser_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankdetails',
            options={'verbose_name': 'bank Detail', 'verbose_name_plural': 'bank Details'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_date'], 'verbose_name': 'education', 'verbose_name_plural': 'education History'},
        ),
        migrations.AlterModelOptions(
            name='workhistory',
            options={'ordering': ['-end_date'], 'verbose_name': 'work history', 'verbose_name_plural': 'work Histories'},
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='date of birth'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='password',
            field=models.CharField(default='admin', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
