# Generated by Django 5.0.1 on 2024-02-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_picture.png', null=True, upload_to='adminuser/profile_pictures', verbose_name='Profile picture'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_picture.png', null=True, upload_to='employees/profile_pictures', verbose_name='Profile picture'),
        ),
    ]
