# Generated by Django 5.0.1 on 2024-02-27 11:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
        ('organizations', '0005_report_category_report_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=datetime.date.today, verbose_name='Report Date')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('attachments', models.FileField(blank=True, upload_to='finance_attachments/', verbose_name='Attachments')),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Revenue')),
                ('total_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Total Expenses')),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Profit/Loss')),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Net Profit')),
                ('gross_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Gross Profit')),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Operating Profit')),
                ('ebitda', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='EBITDA')),
                ('operating_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Operating Expenses')),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Taxes')),
                ('interest_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Interest Expenses')),
                ('profit_margin', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Profit Margin (%)')),
                ('return_on_assets', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Return on Assets (%)')),
                ('return_on_equity', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Return on Equity (%)')),
                ('current_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Current Ratio')),
                ('quick_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Quick Ratio')),
                ('debt_to_equity_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Debt-to-Equity Ratio')),
                ('interest_coverage_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Interest Coverage Ratio')),
                ('asset_turnover_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Asset Turnover Ratio')),
                ('inventory_turnover_ratio', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Inventory Turnover Ratio')),
                ('budgeted_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budgeted Revenue')),
                ('budgeted_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budgeted Expenses')),
                ('budget_variance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Budget Variance')),
                ('forecasted_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Forecasted Revenue')),
                ('forecasted_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Forecasted Expenses')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finances', to='organizations.branch')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_finances', to='employees.adminuser')),
            ],
            options={
                'verbose_name': 'Finance',
                'verbose_name_plural': 'Finances',
                'ordering': ['-report_date'],
            },
        ),
    ]
