# Generated by Django 5.0.1 on 2024-02-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_delegate',
            field=models.BooleanField(default=False, help_text='Designates whether the user can act as a delegate for the organization.', verbose_name='Delegate status'),
        ),
    ]
