# Generated by Django 5.0.1 on 2024-02-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_adminuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived at'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='archived_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived at'),
        ),
        migrations.AddField(
            model_name='employee',
            name='archived_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Archived by'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Archived status'),
        ),
    ]
