# Generated by Django 5.0.1 on 2024-02-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_adminuser_is_delegate'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='can_change_password',
            field=models.BooleanField(default=True, help_text='Designates whether the user can change their password.', verbose_name='Change password status'),
        ),
    ]
