# Generated by Django 5.0.1 on 2024-04-25 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_adminuser_bank_name_alter_adminuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='bank name'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Department/division'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='designation',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Employee', 'Employee'), ('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Associate', 'Associate'), ('Assistant', 'Assistant'), ('Officer', 'Officer'), ('Analyst', 'Analyst'), ('Coordinator', 'Coordinator'), ('Specialist', 'Specialist'), ('Consultant', 'Consultant'), ('Advisor', 'Advisor'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Director', 'Director'), ('Executive', 'Executive'), ('President', 'President'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('CTO', 'CTO'), ('CIO', 'CIO'), ('COO', 'COO'), ('Chairman', 'Chairman'), ('Board Member', 'Board Member'), ('Other', 'Other')], default='Employee', max_length=50, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='employment_status',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated'), ('Resigned', 'Resigned'), ('Retired', 'Retired'), ('Deceased', 'Deceased'), ('On Leave', 'On Leave'), ('On Training', 'On Training'), ('On Probation', 'On Probation'), ('Other', 'Other')], default='Active', max_length=50, verbose_name='Employment status'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('--Select--', '--Select--'), ('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Highest qualification'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='job_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job role'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='level',
            field=models.CharField(blank=True, choices=[('--Select--', '--Select--'), ('Entry-level', 'Entry-level'), ('Mid-level', 'Mid-level'), ('Senior-level', 'Senior-level'), ('Executive', 'Executive'), ('Top-level', 'Top-level'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='bank name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=100, verbose_name='Department/division'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Employee', 'Employee'), ('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Associate', 'Associate'), ('Assistant', 'Assistant'), ('Officer', 'Officer'), ('Analyst', 'Analyst'), ('Coordinator', 'Coordinator'), ('Specialist', 'Specialist'), ('Consultant', 'Consultant'), ('Advisor', 'Advisor'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Director', 'Director'), ('Executive', 'Executive'), ('President', 'President'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('CTO', 'CTO'), ('CIO', 'CIO'), ('COO', 'COO'), ('Chairman', 'Chairman'), ('Board Member', 'Board Member'), ('Other', 'Other')], default='Employee', max_length=50, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated'), ('Resigned', 'Resigned'), ('Retired', 'Retired'), ('Deceased', 'Deceased'), ('On Leave', 'On Leave'), ('On Training', 'On Training'), ('On Probation', 'On Probation'), ('Other', 'Other')], default='Active', max_length=50, verbose_name='Employment status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('--Select--', '--Select--'), ('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='highest_qualification',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Highest qualification'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='job_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='level',
            field=models.CharField(blank=True, choices=[('--Select--', '--Select--'), ('Entry-level', 'Entry-level'), ('Mid-level', 'Mid-level'), ('Senior-level', 'Senior-level'), ('Executive', 'Executive'), ('Top-level', 'Top-level'), ('Other', 'Other')], max_length=100, null=True, verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality'),
        ),
    ]
