# Generated by Django 5.0.1 on 2024-03-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_adminuser_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='asset_turnover_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Asset Turnover Ratio'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='budget_variance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Budget Variance'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='budgeted_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Budgeted Expenses'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='budgeted_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Budgeted Revenue'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='current_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Current Ratio'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='debt_to_equity_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Debt-to-Equity Ratio'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='ebitda',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='EBITDA'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='forecasted_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Forecasted Expenses'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='forecasted_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Forecasted Revenue'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='gross_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Gross Profit'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='interest_coverage_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Interest Coverage Ratio'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='interest_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Interest Expenses'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='inventory_turnover_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Inventory Turnover Ratio'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='net_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Net Profit'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='operating_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Operating Expenses'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='operating_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Operating Profit'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='profit_margin',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Profit Margin (%)'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='quick_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Quick Ratio'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='return_on_assets',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Return on Assets (%)'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='return_on_equity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8, verbose_name='Return on Equity (%)'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='taxes',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Taxes'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='total_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Expenses'),
        ),
        migrations.AlterField(
            model_name='finance',
            name='total_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Revenue'),
        ),
    ]
