# Generated by Django 5.0.1 on 2024-02-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_bankdetails_options_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_status',
            field=models.CharField(blank=True, choices=[('--Select--', '--Select--'), ('Active', 'Active'), ('Inactive', 'Inactive'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated'), ('Resigned', 'Resigned'), ('Retired', 'Retired'), ('Deceased', 'Deceased'), ('On Leave', 'On Leave'), ('On Training', 'On Training'), ('On Probation', 'On Probation'), ('Other', 'Other')], max_length=20, null=True, verbose_name='employee status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('--Select--', '--Select--'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Volunteer', 'Volunteer'), ('Temporary', 'Temporary'), ('Seasonal', 'Seasonal'), ('Freelance', 'Freelance'), ('Remote', 'Remote'), ('Disabled', 'Disabled'), ('Other', 'Other')], max_length=20, null=True, verbose_name='employment status'),
        ),
    ]
