# Generated by Django 5.0.1 on 2024-02-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employee_employee_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='adminuser/', verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_picture.png', null=True, upload_to='employees/', verbose_name='profile picture'),
        ),
    ]
