# Generated by Django 5.0.1 on 2024-02-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_adminuser_archived_at_adminuser_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='archived_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Archived reason'),
        ),
        migrations.AddField(
            model_name='employee',
            name='archived_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Archived reason'),
        ),
    ]
