# Generated by Django 5.0.1 on 2024-02-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_adminuser_can_change_password'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='delegated_branches',
            field=models.ManyToManyField(related_name='authorized_delegates', to='organizations.branch'),
        ),
    ]
