# Generated by Django 5.0.1 on 2024-04-25 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_adminuser_address_alter_adminuser_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number'),
        ),
    ]
