# Generated by Django 5.0.1 on 2024-02-29 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_rename_owner_finance_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_token', to='employees.adminuser'),
        ),
    ]
