# Generated by Django 5.0.1 on 2024-04-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_finance_asset_turnover_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='delegated_branches',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='employment_type',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Volunteer', 'Volunteer'), ('Temporary', 'Temporary'), ('Seasonal', 'Seasonal'), ('Freelance', 'Freelance'), ('Remote', 'Remote'), ('Disabled', 'Disabled'), ('Other', 'Other')], default='Full-time', max_length=100, verbose_name='Employment type'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Intern', 'Intern'), ('Volunteer', 'Volunteer'), ('Temporary', 'Temporary'), ('Seasonal', 'Seasonal'), ('Freelance', 'Freelance'), ('Remote', 'Remote'), ('Disabled', 'Disabled'), ('Other', 'Other')], default='Full-time', max_length=100, verbose_name='Employment type'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(default='April', max_length=20, verbose_name='month'),
        ),
    ]
