# Generated by Django 5.0.1 on 2024-04-25 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_remove_adminuser_delegated_branches_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-updated_at', 'last_name', 'first_name'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='emergency_contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Emergency contacts'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('--Select--', '--Select--'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Other', 'Other')], max_length=30, null=True, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='next_of_kin_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Next of kin phone number'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Emergency contacts'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('--Select--', '--Select--'), ('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated'), ('Other', 'Other')], max_length=30, null=True, verbose_name='Marital status'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='next_of_kin_phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Next of kin phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone number'),
        ),
    ]
