# Generated by Django 5.0.1 on 2024-04-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_adminuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Employee ID'),
        ),
    ]
