# Generated by Django 5.0.1 on 2024-02-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_adminuser_archived_reason_employee_archived_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('--Select--', '--Select--'), ('Annual', 'Annual'), ('Vacation', 'Vacation'), ('Sick', 'Sick'), ('Maternity', 'Maternity'), ('Paternity', 'Paternity'), ('Bereavement', 'Bereavement'), ('Compassionate', 'Compassionate'), ('Study', 'Study'), ('Unpaid', 'Unpaid'), ('Other', 'Other')], max_length=30, null=True, verbose_name='leave type'),
        ),
    ]
