# Generated by Django 5.0.1 on 2024-02-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_adminuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(max_length=30, unique=True, verbose_name='employee ID'),
        ),
    ]
