# Generated by Django 5.0.1 on 2024-02-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_picture.png', null=True, upload_to='adminuser/', verbose_name='profile picture'),
        ),
    ]
