# Generated by Django 5.0.1 on 2024-04-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='designation',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Employee', 'Employee'), ('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Associate', 'Associate'), ('Assistant', 'Assistant'), ('Officer', 'Officer'), ('Analyst', 'Analyst'), ('Coordinator', 'Coordinator'), ('Specialist', 'Specialist'), ('Consultant', 'Consultant'), ('Advisor', 'Advisor'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Director', 'Director'), ('Executive', 'Executive'), ('President', 'President'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('CTO', 'CTO'), ('CIO', 'CIO'), ('COO', 'COO'), ('Chairman', 'Chairman'), ('Board Member', 'Board Member'), ('Other', 'Other')], default='Employee', max_length=50, verbose_name='Designation'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(choices=[('--Select--', '--Select--'), ('Employee', 'Employee'), ('Intern', 'Intern'), ('Trainee', 'Trainee'), ('Associate', 'Associate'), ('Assistant', 'Assistant'), ('Officer', 'Officer'), ('Analyst', 'Analyst'), ('Coordinator', 'Coordinator'), ('Specialist', 'Specialist'), ('Consultant', 'Consultant'), ('Advisor', 'Advisor'), ('Supervisor', 'Supervisor'), ('Manager', 'Manager'), ('Director', 'Director'), ('Executive', 'Executive'), ('President', 'President'), ('CEO', 'CEO'), ('CFO', 'CFO'), ('CTO', 'CTO'), ('CIO', 'CIO'), ('COO', 'COO'), ('Chairman', 'Chairman'), ('Board Member', 'Board Member'), ('Other', 'Other')], default='Employee', max_length=50, verbose_name='Designation'),
        ),
    ]
