# Generated by Django 5.0.1 on 2024-02-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_leave_leave_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_end_date',
            field=models.DateField(null=True, verbose_name='leave end date'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_reason',
            field=models.TextField(null=True, verbose_name='leave reason'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_start_date',
            field=models.DateField(null=True, verbose_name='leave start date'),
        ),
    ]
