# Generated by Django 5.0.1 on 2024-04-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_adminuser_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuser',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State of origin'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state_of_origin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State of origin'),
        ),
    ]
