# Generated by Django 5.0.1 on 2024-02-19 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_alter_leave_leave_end_date_alter_leave_leave_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='absent_penalty',
            field=models.IntegerField(default=0, verbose_name='absent penalty'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='late_penalty',
            field=models.IntegerField(default=0, verbose_name='late penalty'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='overtime_bonus',
            field=models.IntegerField(default=0, verbose_name='overtime bonus'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='performance_bonus',
            field=models.IntegerField(default=0, verbose_name='performance bonus'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='performance_penalty',
            field=models.IntegerField(default=0, verbose_name='performance penalty'),
        ),
    ]
