# Generated by Django 5.0.1 on 2024-02-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_payroll_absent_penalty_payroll_late_penalty_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='salary',
            new_name='basic_salary',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='salary',
            new_name='basic_salary',
        ),
    ]
