# Generated by Django 5.0.1 on 2024-02-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_rename_salary_adminuser_basic_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='month',
            field=models.CharField(default=2, max_length=20, verbose_name='month'),
        ),
    ]
