# Generated by Django 5.0.1 on 2024-02-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_adminuser_basic_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='other_allowance',
            field=models.IntegerField(default=0, verbose_name='other allowances'),
        ),
    ]
