# Generated by Django 5.0.1 on 2024-02-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_payroll_absent_penalty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Delayed', 'Delayed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, verbose_name='payment status'),
        ),
    ]
