# Generated by Django 5.0.1 on 2024-02-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_payroll_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='account number'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='bank name'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='pension_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='pension ID'),
        ),
        migrations.AddField(
            model_name='adminuser',
            name='tax_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='tax ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='account number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='bank name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='pension_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='pension ID'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tax_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='tax ID'),
        ),
        migrations.DeleteModel(
            name='BankDetails',
        ),
    ]
