# Generated by Django 5.0.1 on 2024-02-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_adminuser_account_number_adminuser_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='next_of_kin_address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='next_of_kin_address',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='account name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='account name'),
        ),
    ]
