# Generated by Django 5.0.1 on 2024-04-25 19:06

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('org_id', models.CharField(max_length=12, unique=True, verbose_name='organization id')),
                ('industry', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Manufacturing', 'Manufacturing'), ('Education', 'Education'), ('Retail', 'Retail'), ('Hospitality', 'Hospitality'), ('Other', 'Other')], max_length=100, verbose_name='industry')),
                ('sector', models.CharField(blank=True, max_length=200, verbose_name='sector')),
                ('size', models.CharField(blank=True, choices=[('1 - 20', '1 - 20'), ('21 - 100', '21 - 100'), ('101 - 500', '101 - 500'), ('501 - 1000', '501 - 1000'), ('Above 1000', 'Above 1000')], default='1 - 20', max_length=100, verbose_name='size')),
                ('branches', models.CharField(blank=True, choices=[('1 - 10', '1 - 10'), ('10 - 50', '10 - 50'), ('51 - 100', '51 - 100'), ('101 - 500', '101 - 500'), ('Above 500', 'Above 500')], default='1 - 10', max_length=100, verbose_name='branches')),
                ('headquarter', models.CharField(blank=True, max_length=250, null=True, verbose_name='headquarter')),
                ('website', models.URLField(blank=True, max_length=250, null=True, verbose_name='website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact phone')),
                ('contact_email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='contact email')),
                ('mailing_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='mailing address')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='annual revenue')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='annual profit')),
                ('employee_benefits', models.TextField(blank=True, null=True, verbose_name='employee benefits')),
                ('facebook', models.URLField(blank=True, max_length=250, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, max_length=250, null=True, verbose_name='twitter')),
                ('linkedin', models.URLField(blank=True, max_length=250, null=True, verbose_name='linkedin')),
                ('monthly_created_employees', models.PositiveIntegerField(default=0, verbose_name='monthly employees added')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='certifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='employees.adminuser')),
                ('hierarchy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('branch_id', models.CharField(max_length=5, unique=True, verbose_name='branch id')),
                ('location', models.CharField(max_length=250, verbose_name='location')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact phone')),
                ('contact_email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='contact email')),
                ('facebook', models.URLField(blank=True, max_length=250, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, max_length=250, null=True, verbose_name='twitter')),
                ('linkedin', models.URLField(blank=True, max_length=250, null=True, verbose_name='linkedin')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('monthly_created_employees', models.PositiveIntegerField(default=0, verbose_name='monthly employees added')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_branches', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrgDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100, verbose_name='document name')),
                ('document', models.FileField(upload_to='organizations/documents/', verbose_name='document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['document_name', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField(default=datetime.date.today, verbose_name='Report Date')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('ad-hoc', 'Ad-hoc')], default='monthly', max_length=20, verbose_name='Report Type')),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('performance', 'Performance'), ('employee', 'Employee'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('inventory', 'Inventory'), ('customer_service', 'Customer Service'), ('production', 'Production'), ('quality_control', 'Quality Control'), ('research_and_development', 'Research and Development'), ('human_resources', 'Human Resources'), ('training_and_development', 'Training and Development'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
                ('comments', models.TextField(blank=True, verbose_name='Comments')),
                ('attachments', models.FileField(blank=True, upload_to='report_attachments/', verbose_name='Attachments')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_reports', to='employees.adminuser')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'ordering': ['-report_date'],
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Reason for Transfer')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transfers', to='employees.adminuser')),
                ('destination_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='organizations.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_history', to='employees.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='organizations.organization')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_transfers', to='employees.adminuser')),
                ('source_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transfers', to='organizations.branch')),
            ],
            options={
                'verbose_name': 'Transfer',
                'verbose_name_plural': 'Transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
