# Generated by Django 5.0.1 on 2024-02-12 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('industry', models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Finance', 'Finance'), ('Manufacturing', 'Manufacturing'), ('Education', 'Education'), ('Retail', 'Retail'), ('Hospitality', 'Hospitality'), ('Other', 'Other')], max_length=100, verbose_name='industry')),
                ('sector', models.CharField(blank=True, max_length=200, verbose_name='sector')),
                ('size', models.CharField(blank=True, choices=[('1 - 20', '1 - 20'), ('21 - 100', '21 - 100'), ('101 - 500', '101 - 500'), ('501 - 1000', '501 - 1000'), ('Above 1000', 'Above 1000')], default='1 - 20', max_length=100, verbose_name='size')),
                ('branches', models.CharField(blank=True, choices=[('1 - 10', '1 - 10'), ('10 - 50', '10 - 50'), ('51 - 100', '51 - 100'), ('101 - 500', '101 - 500'), ('Above 500', 'Above 500')], default='1 - 10', max_length=100, verbose_name='branches')),
                ('headquarter', models.CharField(blank=True, max_length=250, null=True, verbose_name='headquarter')),
                ('website', models.URLField(blank=True, max_length=250, null=True, verbose_name='website')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact phone')),
                ('contact_email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='contact email')),
                ('mailing_address', models.CharField(blank=True, max_length=250, null=True, verbose_name='mailing address')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='annual revenue')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='annual profit')),
                ('employee_benefits', models.TextField(blank=True, null=True, verbose_name='employee benefits')),
                ('facebook', models.URLField(blank=True, max_length=250, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, max_length=250, null=True, verbose_name='twitter')),
                ('linkedin', models.URLField(blank=True, max_length=250, null=True, verbose_name='linkedin')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='certifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='employees.adminuser')),
                ('hierarchy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subsidiaries', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'organization',
                'verbose_name_plural': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('location', models.CharField(max_length=250, verbose_name='location')),
                ('email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='email')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='contact phone')),
                ('contact_email', models.EmailField(blank=True, max_length=250, null=True, verbose_name='contact email')),
                ('facebook', models.URLField(blank=True, max_length=250, null=True, verbose_name='facebook')),
                ('twitter', models.URLField(blank=True, max_length=250, null=True, verbose_name='twitter')),
                ('linkedin', models.URLField(blank=True, max_length=250, null=True, verbose_name='linkedin')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_branches', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'branch',
                'verbose_name_plural': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrgDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100, verbose_name='document name')),
                ('document', models.FileField(upload_to='organizations/documents/', verbose_name='document')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['document_name', '-created_at'],
            },
        ),
    ]
