# Generated by Django 5.0.1 on 2024-02-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_monthly_created_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='monthly_created_employees',
            field=models.PositiveIntegerField(default=0, verbose_name='monthly employees added'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='monthly_created_employees',
            field=models.PositiveIntegerField(default=0, verbose_name='monthly employees added'),
        ),
    ]
