# Generated by Django 5.0.1 on 2024-02-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_transfer_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='Pending', max_length=20, verbose_name='Status'),
        ),
    ]
