# Generated by Django 5.0.1 on 2024-02-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_remove_report_owner_report_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('financial', 'Financial'), ('performance', 'Performance'), ('employee', 'Employee'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('inventory', 'Inventory'), ('customer_service', 'Customer Service'), ('production', 'Production'), ('quality_control', 'Quality Control'), ('research_and_development', 'Research and Development'), ('human_resources', 'Human Resources'), ('training_and_development', 'Training and Development'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('ad-hoc', 'Ad-hoc')], default='monthly', max_length=20, verbose_name='Report Type'),
        ),
    ]
